export const modalStyles = {
  overlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  content: (darkMode) => ({
    position: 'relative',
    background: darkMode ? '#16181C' : '#ffffff',
    borderRadius: '16px',
    border: `1px solid ${darkMode ? '#2F3336' : '#EFF3F4'}`,
    padding: '24px',
    maxWidth: '90%',
    maxHeight: '90vh',
    width: 'auto',
    overflow: 'auto',
    color: darkMode ? '#E7E9EA' : '#0F1419',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    inset: 'auto',
  }),
  closeButton: (darkMode) => ({
    position: 'absolute',
    top: '12px',
    right: '12px',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '8px',
    borderRadius: '50%',
    color: darkMode ? '#71767B' : '#536471',
    '&:hover': {
      backgroundColor: darkMode ? '#1D1F23' : '#F7F9F9',
      color: darkMode ? '#E7E9EA' : '#0F1419',
    },
  }),
  header: {
    marginBottom: '16px',
    fontSize: '20px',
    fontWeight: '700',
  },
  footer: (darkMode) => ({
    marginTop: '24px',
    paddingTop: '16px',
    borderTop: `1px solid ${darkMode ? '#2F3336' : '#EFF3F4'}`,
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
  }),
};
